### ISSUE TITLE
リリース 1.0.0 [2018.11]

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/THECARDGAME#42]
# THE CARD GAME ホームページ作成
- [x] ホームページ 更新 #1  
- [x] カード入手方法
- [x] ぴんきー 新規ページ作成 #27 
- [x] 関連ページ　素敵曜日ナイトスクーる #29
- [x]  PAI ID作成 [feature 1.0.0] #28

# THE CARD GAME カード作成
## 素敵曜日ナイトスクーる
- [ ] 釘町みやび
- [ ] こまいけんと
- [ ] 伊藤麻衣
## 岡本美緒
- [ ] 岡本美緒 レイヤーカード[１０月ハロウィン] #39  
- [ ] 岡本美緒 普及カード[１０月普及カード] #30 
- [ ] 岡本美緒 推しカード[１０月推しカード] #35 
- [ ] 岡本美緒 普及カード[１１月普及カード] #31  
- [ ] 岡本美緒 推しカード[１１月推しカード] #33  
- [ ] 岡本美緒 アイテムカード[アイスマニア] #41
